import { ApiProvider } from '@/lib/query-client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'react-datepicker/dist/react-datepicker.css';
import { Toaster } from 'sonner';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <ApiProvider>{children}</ApiProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
